routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('settings/password','SettingsController@editPassword');
Route::post('settings/password','SettingsController@updatePassword');
Route::get('settings/profile','SettingsController@profile');
Route::get('settings/profile/edit', 'SettingsController@editProfile'); 
Route::post('settings/profile', 'SettingsController@updateProfile');
Route::get('auth/verify/{token}','Auth\RegisterController@verify');
Route::get('auth/send-verification', 'Auth\RegisterController@sendVerification');
Route::get('/','GuestController@index'); 
Route::get('books/{book}/borrow',[
     'middleware' => ['auth', 'role:member'],
      'as' => 'guest.books.borrow', 
      'uses' => 'BooksController@borrow'
      ]);

Route::put('books/{book}/return',[
'middleware' => ['auth','role:member'],
'as' => 'member.books.return',
'uses' => 'BooksController@returnBack'
]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'web'], function(){
    
    Route::group(['prefix'=> 'admin','middleware' => ['auth','role:admin']], function(){
    Route::resource('authors','AuthorsController');
    Route::resource('books','BooksController');
    Route::resource('members','MembersController');
    Route::get('statistics',[
        'as'=>'statistics.index',
        'uses'=>'StatisticsController@index'
    ]);
});
});

app/Book.php
<?php

namespace App;
use Illuminate\Support\Facades\Session;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{


    protected $fillable = ['title','author_id','amount'];
    public function author(){
        return $this->belongsTo('App\Author');
    }

    public function borrowLogs()
    {
        return $this->hasMany('App\BorrowLog');
    }
    public function getStockAttribute()
    {
        $borrowed = $this->borrowLogs()->borrowed()->count();
        $stock = $this->amount-$borrowed;
        return $stock;
    }
    public static function boot(){
        parent::boot();
        self::updating(function($book){
            if ($book->amount < $book->borrowed){
                Session::flash("flash_notification",[
                    "level" => "danger",
                    "message"=> "Jumlah Buku $book->title harus >=".$book->borrowed
                ]);

                return false;

            }

        });
        self::deleting(function($book){
            if($book->borrowLogs()->count() > 0){
                Session::flash("flash_notification",[
                    "level" =>"danger",
                    "message" =>"Buku $book->title Sedang di pinjam"

                ]);
                return false;

            }
        });

    }
    public function getBorrowedAttribute(){
        return $this->borrowLogs()->borrowed()->count();
    }

}

app/Http/Controllers/BooksController.php
<?php
namespace App\Http\Controllers;
use App\Book;
use Illuminate\Database\Eloquent\ModelNotFoundException; 
use App\BorrowLog; 
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Yajra\Datatables\Datatables;
use App\Http\Requests\StoreBookRequest;
use App\Http\Requests\UpdateBookRequest;
use Yajra\Datatables\Html\Builder;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;
use App\Exceptions\BookException;

class BooksController extends Controller
{
    public function borrow($id) {
        try { 
            $book = Book::findOrFail($id); 
          Auth::user()->borrow($book);

             Session::flash("flash_notification", [ 
             "level"=>"success",
              "message"=>"Berhasil meminjam $book->title" 
              ]);
             }catch(BookException $e){
                 Session::flash("flash_notification",[
                     "level" =>"danger",
                     "message"=> $e->getMessage()
                 ]);
             }catch(ModelNotFoundException $e){
                 Session::flash("flash_notification",[
                     "level" => "danger",
                     "message" =>"Buku Tidak di temukan."
                 ]);
             }
    

    return redirect('/');
    }
    
public function returnBack($book_id){
    $borrowLog = BorrowLog::where('user_id',Auth::user()->id)
    ->where('book_id',$book_id)
    ->where('is_returned',0)
    ->first();

    if($borrowLog){
        $borrowLog->is_returned = true;
        $borrowLog->save();

        Session::flash("flash_notification" ,[
            "level" => "success",
            "message" => "Berhasil mengembalikan" . $borrowLog->book->title
        ]);
    }
    return redirect('/home');
}

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Builder $htmlBuilder)
    {
if ($request->ajax()){
    $books = Book::with('author');
    return Datatables::of($books)
    ->addColumn('action',function($book){
        return view('datatable._action',[
            'model' => $book,
            'form_url' => route('books.destroy',$book->id),
            'edit_url'=>route('books.edit',$book->id),
            'confirm_message' => 'Yakin mau menghapus'.$book->title.'?'
            ]);
    })->make(true);

}   
$html = $htmlBuilder 
->addColumn(['data' => 'title', 'name'=>'title', 'title'=>'Judul']) 
->addColumn(['data' => 'amount', 'name'=>'amount', 'title'=>'Jumlah']) 
->addColumn(['data' => 'author.name', 'name'=>'author.name', 'title'=>'Penulis']) 
->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>true, 'searchable'=>false]);     
return view('books.index')->with(compact('html'));    
}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBookRequest $request)
    {
      
        $book = Book::create($request->except('cover'));
        //isi field cover jika ada cover yg di upload
        if($request->hasFile('cover')){
            //Mengambil file yg di upload
            $uploaded_cover = $request->file('cover');
            //Mengambil extension file
            $extension = $uploaded_cover->getClientOriginalExtension();
            //Membuat nama file random berikut extension
            $filename = md5(time()) . '.' . $extension;
            //Menyimpan cover ke folder public/img
            $destinationPath = public_path().DIRECTORY_SEPARATOR.'img';
            $uploaded_cover->move($destinationPath,$filename);
            //Mengisi field cover di book dengan filename yang baru di buat 
            $book->cover = $filename;
            $book->save();

        } 
        Session::flash("flash_notification",[
            "level"=>"success",
            "message"=>"Berhasil Menyimpan $book->title"

        ]);
        return redirect()->route('books.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::find($id); 
        return view('books.edit')->with(compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBookRequest $request, $id)
    {
        
$book = Book::find($id);
if(!$book->update($request->all())) return redirect()->back();
if ($request->hasFile('cover')) { // menambil cover yang diupload berikut ekstensinya
    $filename = null; 
    $uploaded_cover = $request->file('cover');
    $extension = $uploaded_cover->getClientOriginalExtension();
// membuat nama file random dengan extension 
$filename = md5(time()) . '.' . $extension;
 $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';
// memindahkan file ke folder public/img 
$uploaded_cover->move($destinationPath, $filename);
// hapus cover lama, jika ada
 if ($book->cover) {
      $old_cover = $book->cover;
       $filepath = public_path() . DIRECTORY_SEPARATOR . 'img' .
        DIRECTORY_SEPARATOR . $book->cover;
try { 
    File::delete($filepath);
 } catch (FileNotFoundException $e) { 
     // File sudah dihapus/tidak ada
     }
}
// ganti field cover dengan cover yang baru
$book->cover = $filename;
 $book->save();
}
Session::flash("flash_notification",
 [ "level"=>"success", "message"=>"Berhasil Mengubah buku $book->title"
  ]);
return redirect()->route('books.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);
        $cover = $book->cover;
        if(!$book->delete())return redirect()->back();
        // Hapus cover lama , jika ada
        if($cover){
            $old_cover = $book->cover;
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'img' .
             DIRECTORY_SEPARATOR . $book->cover;
try {
     File::delete($filepath); 
} catch (FileNotFoundException $e){
     // File sudah dihapus/tidak ada
 }

}

Session::flash("flash_notification",[
    "level"=>"success",
    "message"=>"Buku Berhasil di hapus"
]);
return redirect()->route('books.index');

    }
}

resources/views/books/_form.blade.php
<div class="form-group{{$errors->has('title') ? 'has-eror': '' }}">
{!! Form::label('title','Judul',['class'=>'col-md-2 control-label']) !!}
<div class="col-md-4">
{!! Form::text('title',null,['class'=>'form-control']) !!}
{!! $errors->first('title','<p class="help-block">:message</p>') !!}
</div>
</div>
<div class="form-group {!! $errors->has('author_id') ? 'has-error' : '' !!}">
 {!! Form::label('author_id', 'Penulis', ['class'=>'col-md-2 control-label']) !!} 
 <div class="col-md-4"> 
 {!! Form::select('author_id', [''=>'']+App\Author::pluck('name','id')->all(), null,[
 'class'=>'js-selectize',
 'placeholder'=>'Pilih Penulis']) !!} 
 {!! $errors->first('author_id', '<p class="help-block">:message</p>') !!} 
 </div>
  </div>
<div class="form-group{{ $errors->has('amount') ? ' has-error' : '' }}"> 
{!! Form::label('amount', 'Jumlah', ['class'=>'col-md-2 control-label']) !!}
 <div class="col-md-4"> 
{!! Form::number('amount', null, ['class'=>'form-control', 'min'=>1]) !!} 
{!! $errors->first('amount', '<p class="help-block">:message</p>') !!} 
@if (isset($book))
<p class="help-block">{{$book->borrowed}} buku sedang di pinjam</p>

@endif
</div>
 </div>
<div class="form-group{{ $errors->has('cover') ? ' has-error' : '' }}"> 
{!! Form::label('cover', 'Jumlah', ['class'=>'col-md-2 control-label']) !!} 
<div class="col-md-4">

{!! Form::file('cover') !!}
@if(isset($book) && $book->cover)
<p>
{!! Html::image(asset('img/'.$book->cover),null,['class'=>'img-rounded img-responsive']) !!}</p>
@endif
 {!! $errors->first('cover', '<p class="help-block">:message</p>') !!} 
</div> 
</div>

<div class="form-group">
<div class="col-md-4 col-md-offset-2">
{!! Form::submit('Simpan',['class'=>'btn btn-primary']) !!}
</div>
</div>

resources/views/books/create.blade.php
@extends('layouts.app')
@section('content') 
<div class="container"> 
<div class="row">
 <div class="col-md-12">
  <ul class="breadcrumb"> <li><a href="{{ url('/home') }}">Dashboard</a></li>
 <li><a href="{{ url('/admin/books') }}">Buku</a></li>
  <li class="active">Tambah Buku</li> </ul> 
  <div class="panel panel-default"> 
  <div class="panel-heading"> 
  <h2 class="panel-title">Tambah Buku</h2>
  </div>
<div class="panel-body">
 {!! Form::open(['url' => route('books.store'), 'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!} 
 @include('books._form') 
 {!! Form::close() !!} 
 </div> 
 
 </div> 
 </div> 
 </div> 
 </div>
  @endsection

resources/views/books/edit.blade.php
@extends ('layouts.app')

@section('content')

<div class="container">
<div class="row">
<div class="col-md-12">
<ul class="breadcrumb">
<li><a href="{{url('/home') }}">Dashboard</a></li>
<li><a href="{{url('/admin/books')}}">Buku</a></li>
<li class="active">Ubah Buku</li>
</ul>
<div class="panel panel-default">
<div class="panel-heading">
<h2 class="panel-title">Ubah buku</h2>
</div>
<div class="panel-body">
{!! Form::model($book,['url'=>route('books.update',$book->id),
'method'=>'put','files'=>'true','class'=>'form-horizontal'])  !!}
@include('books._form')
{!! Form::close() !!}
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/books/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row">
<div class="col-md-12">
<ul class="breadcrumb">
<li><a href="{{url('/home')}}">Dashboard</a></li>
<li class="active">Buku</li>
</ul>
<div class="panel panel-default">
<div class="panel-heading">
<h2 class="panel-title">Buku</h2>
</div>
<div class="panel-body">
<p> <a class="btn btn-primary" href="{{url('/admin/books/create')}}">Tambah</a></p>
{!! $html->table(['class'=>'table-striped']) !!}
</div>
</div>
</div>
</div>
</div>
@endsection
@section('scripts')
{!!  $html->scripts() !!}
@endsection