routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('settings/password','SettingsController@editPassword');
Route::post('settings/password','SettingsController@updatePassword');
Route::get('settings/profile','SettingsController@profile');
Route::get('settings/profile/edit', 'SettingsController@editProfile'); 
Route::post('settings/profile', 'SettingsController@updateProfile');
Route::get('auth/verify/{token}','Auth\RegisterController@verify');
Route::get('auth/send-verification', 'Auth\RegisterController@sendVerification');
Route::get('/','GuestController@index'); 
Route::get('books/{book}/borrow',[
     'middleware' => ['auth', 'role:member'],
      'as' => 'guest.books.borrow', 
      'uses' => 'BooksController@borrow'
      ]);

Route::put('books/{book}/return',[
'middleware' => ['auth','role:member'],
'as' => 'member.books.return',
'uses' => 'BooksController@returnBack'
]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'web'], function(){
    
    Route::group(['prefix'=> 'admin','middleware' => ['auth','role:admin']], function(){
    Route::resource('authors','AuthorsController');
    Route::resource('books','BooksController');
    Route::resource('members','MembersController');
    Route::get('statistics',[
        'as'=>'statistics.index',
        'uses'=>'StatisticsController@index'
    ]);
});
});

resources/views/layouts/_flash.blade.php
@if (session()->has('flash_notification.message'))
<div class="container">
<div class="alert alert-{{session()->get('flash_notification.level') }}">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
{!! session()->get('flash_notification.message') !!}
</div>
</div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="rel="stylesheet" type="text/css" {{asset('css/font-awesome.min.css')}}" > 
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/app.css')}}" rel="stylesheet">
    <link href="/css/selectize.css" rel="stylesheet"> 
    <link href="/css/selectize.bootstrap3.css" rel="stylesheet"> 
    <link href="{{asset('css/jquery.dataTables.css')}}" rel="stylesheet">
    <link href="rel="stylesheet" type="text/css" {{asset('css/dataTables.bootstrap.css')}}" >
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                        @if (Auth::check()) 
                        <li><a href="{{ url('/home') }}">Dashboard</a></li>
                        
                         @endif 
                         @role('admin') 
                         <li>
                         <a href="{{ route('authors.index') }}">Penulis</a>
                         </li>
                         <li>
                         <a href="{{route('books.index')}}">Buku</a>
                         </li>
                         <li>
                         <a href="{{route('members.index')}}">Member</a>
                         </li>
                          <li>
                          <a href="{{route('statistics.index') }}">Peminjaman</a>
                          </li>  
                         @endrole 
                        
                         @if (auth()->check())
                          <li>
                          <a href="{{ url('/settings/profile') }}">Profile</a>
                          </li> 
                          @endif 

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Daftar</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                         <li><a href="{{ url('/settings/password') }}"><i class="fa fa-btn fa-lock"></i>Ubah Password</a></li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
        @include('layouts._flash')
        @yield('content')
    </div>

    <!-- Scripts -->
    
    <script type ="text/javascript"src="{{asset('js/jquery-3.3.1.min.js') }}"></script> 
    <script type ="text/javascript"src="{{asset('js/jquery.dataTables.min.js')}}"> </script> 
    <script type ="text/javascript"src="/js/dataTables.bootstrap.min.js"></script>  
   
    <script src="{{asset('js/bootstrap.min.js')}}"></script> 
    <script src="{{asset('js/selectize.min.js')}}"></script>
    <script src="{{asset('js/custom.js')}}"></script>
  
    @yield('scripts')   

   
</body>
</html>